### ISSUE TITLE
deprecation notice for katello-agent from Red Hat

### ISSUE THREAD

**Issue by dannygoulder** [waveclaw/puppet-subscription_manager#109]
Red Hat have [indicated ](https://bugzilla.redhat.com/show_bug.cgi?id=1867774) with the latest release of Satellite that katello-agent is now deprecated.

That's good news for me as goferd has long been plagued with memory leaks causing issues for our Red Hat estate.

However, I think this module depends on the presence of katello-agent for some of its functionality.

I'm happy to help out figuring out what impact the removal of katello-agent would cause for this module, but I'll raise this issue anyway in case maintainers weren't aware.

**Comment by waveclaw** [comment]
There should be no impact if the advanced methodology is used where you pull parts ala carte.  

For the overall module where a users is just 'clicking okay and go,; version detection for including the katello-agent is needed so that it can be optional by default.

**Comment by waveclaw** [comment]
Removed service from core requirements in top-level module
