### ISSUE TITLE
action happening each puppet agent run 

### ISSUE THREAD

**Issue by AlexSamad** [waveclaw/puppet-subscription_manager#111]
Hi

This is what i have to kick it off

  class { 'subscription_manager':
    org           => 'ORG',
    activationkey   => 'pp_r20210405',
    autosubscribe => true,
    servicelevel  => 'SELF-SUPPORT',
    ca_package    => false,
    config_hash => {
      server_proxy_hostname        => 'proxy',
      server_proxy_port            => 3128,
    },
    service_name    =>'rhsmcertd',
  }

But every time i get this 

Notice: /Stage[main]/Subscription_manager::Config/Rhsm_register[subscription.rhn.redhat.com]/ensure: created (corrective)

Not sure what its doing and why it needs to do it every time I run --test

**Comment by waveclaw** [comment]
When you run with '--test' then the Puppet doesn't actually do anything. Puppet will run stuff to check the system but not things to change the system. So every time the '--test' is run, all the actions that would have happened are run.  That includes this (fake) attempt to create a configuration in /etc/rhsm/rhsm.conf for your self-supported registration.
