### ISSUE TITLE
New machine hangs

### ISSUE THREAD

**Issue by benohara** [waveclaw/puppet-subscription_manager#113]
A mahcines thats not subscribed seems to hang whislt running the facts to gather repos etc on the initial run.

Debug: Facter: Network error, unable to connect to server. Please see /var/log/rhsm/rhsm.log for more information.
Debug: Facter: process exited with status code 70.
Debug: Facter: fact "rhsm_available_repos" has resolved to [].
Debug: Facter: executing command: /usr/bin/sh -c /usr/sbin/subscription-manager list --consumed
Debug: Facter: No consumed subscription pools were found.
Debug: Facter: process exited with status code 0.
Debug: Facter: fact "rhsm_disabled_pools" has resolved to [].
Debug: Facter: executing command: /usr/bin/sh -c /usr/sbin/subscription-manager repos

They appear to timeout in the end, but could they be set to only execute if its subscribed?

**Comment by waveclaw** [comment]
That would require asking subscriptoin_manager if the server is subscribed, which also caused a hang as the system tries to lookup the registration with the satellite server.

There are ways to guess this but nothing reliable or useful.  A possible workaround is to flood the cache with empty or filler values.
