### ISSUE TITLE
rhsm_config not changing parameters

### ISSUE THREAD

**Issue by ralfbosz** [waveclaw/puppet-subscription_manager#117]
The newest release does not change the rhsm.conf parameters with rhsm_config:

```
rhsm_config { '/etc/rhsm/rhsm.conf':
  server_port => '8443',
}
```

A run shows:

`Notice: /Stage[main]/Main/Rhsm_config[/etc/rhsm/rhsm.conf]/server_port: server_port changed 443 to '8443'
`
But the parameter is not changed:

```
# Server port:
port = 443
```

Every run the parameter is changed according to the run, but never for real.

Also the help-file says the 'name' of the parameter should be the satellite-capsule, but when setting that an error shows only a valid path is possible:

`Error: Parameter name failed on Rhsm_config[sattelite.com]: Validate method failed for class name: Require an absolute path ending in a filename.`

**Comment by markasammut** [comment]
Same issue happening. Each run returns:

Notice: /Stage[main]/Subscription_manager::Config/Rhsm_config[/etc/rhsm/rhsm.conf]/rhsm_full_refresh_on_yum: rhsm_full_refresh_on_yum changed 1 to 0 (corrective)

But the parameter is left as '1':

```
[root| ~]# cat /etc/rhsm/rhsm.conf | grep refresh
full_refresh_on_yum = 1
```

**Comment by vchepkov** [comment]
same, for 3 parameters on RHEL8

```
Jun 23 09:57:10 example puppet-agent[130998]: (/Stage[main]/Subscription_manager::Config/Rhsm_config[/etc/rhsm/rhsm.conf]/rhsm_baseurl) rhsm_baseurl changed 'https://satellite/pulp/content/' to 'https://satellite/pulp/repos' (corrective)
Jun 23 09:57:10 example puppet-agent[130998]: (/Stage[main]/Subscription_manager::Config/Rhsm_config[/etc/rhsm/rhsm.conf]/rhsm_full_refresh_on_yum) rhsm_full_refresh_on_yum changed 1 to 0 (corrective)
Jun 23 09:57:10 example puppet-agent[130998]: (/Stage[main]/Subscription_manager::Config/Rhsm_config[/etc/rhsm/rhsm.conf]/rhsmcertd_autoattachinterval) rhsmcertd_autoattachinterval changed 1440 to 60 (corrective)
```

**Comment by vchepkov** [comment]
FYI, downgrading to v5.6.3 makes parameters to be modified, but it has other issues:

```
Error: Facter: error while resolving custom fact "rhsm_identity": undefined method `rhsm_environment' for Facter::Util::RhsmEnvironment:Module
```
