### ISSUE TITLE
1.9.3 seems to set rhsm_baseurl to cdn.redhat.com without clean way to override

### ISSUE THREAD

**Issue by jcpunk** [waveclaw/puppet-subscription_manager#12]
The value for Rhsm_config[/etc/rhsm/rhsm.conf]/rhsm_baseurl seems to come out of defaults.pp.  Where it points to cdn.redhat.com

To get the "auto generated" url it appears I need to duplicate the config hash.  A cleaner option would be nice.

**Comment by waveclaw** [comment]
This is by design - to setup a complete list of options in hiera.
