### ISSUE TITLE
Types are empty

### ISSUE THREAD

**Issue by yannickstruyf** [waveclaw/puppet-subscription_manager#16]
Dear,

after installation of version 1.11.0 we noticed the types folder is empty.
Version 1.10.1 seems OK.

Kind regards

**Comment by waveclaw** [comment]
Do you mean /lib/puppet/type?

There is no 'types' folder in this module.  

I checked the uploaded package tarball sent to forge.puppetlabs.com and it does contain the custom type definitions.  

The same set of native types was found in the v1.11.0 tag as in the v1.10.1.  All the expected /lib/puppet/type contents are present and have not changed significantly.

```
subscription_manager/lib/puppet/$ tree type
type
├── rhsm_config.rb
├── rhsm_override.rb
├── rhsm_pool.rb
├── rhsm_register.rb
└── rhsm_repo.rb

0 directories, 5 files
subscription_manager/lib/puppet/$ git status
HEAD detached at v1.10.1
nothing to commit, working directory clean

subscription_manager/lib/puppet/$ git checkout v1.11.0
Previous HEAD position was 1125a48... updates for 1.10.1 with documentation and examples
HEAD is now at 537625a... vesion 1.11.0 with cached facts, documented features
subscription_manager/lib/puppet/$ tree type
type
├── rhsm_config.rb
├── rhsm_override.rb
├── rhsm_pool.rb
├── rhsm_register.rb
└── rhsm_repo.rb

0 directories, 5 files
```

**Comment by waveclaw** [comment]
Closing with 'no response.'
