### ISSUE TITLE
ca consumer not up-to-date

### ISSUE THREAD

**Issue by yuri2801** [waveclaw/puppet-subscription_manager#17]
Hi,

I had to change the CA consummer on my satellite, but puppet didn't update the package. I change the package of the consumer from installed to latest, and it update it. 

I suggest that change to improve your module.

Kind regards,

Yuri

**Comment by waveclaw** [comment]
I thank you for bringing this up as an issue.  The defaults are conservative. 

Working currently on a release to address this and the caching issues with repositories.  

 I have no ETA for any update.  My lab is down at the moment to do testing.

**Comment by waveclaw** [comment]
fixed with 1.12.1
