### ISSUE TITLE
Facter Libs Not Working

### ISSUE THREAD

**Issue by Ramorous** [waveclaw/puppet-subscription_manager#23]
The following snippet of code just isn't working for me in my environment.

```
    confine do
      File.exist? '/usr/sbin/subscription-manager'
    end
# OR
  confine { File.exist? '/usr/sbin/subscription-manager' }
```

Environment: RHEL 7.2 running Red Hat Satellite 6.1

When running puppet agent, it find that rhsm_identity is blank. I comment that part out and it works perfectly.

**Comment by Ramorous** [comment]
Ways I produced the output.
In the config.pp manifest, added a notify to output the contents of the rhsm_identity call and nothing came out.

From command line:
export FACTERLIB=~/lib/facter:$FACTERLIB
cp /etc/puppet/modules/subscription_manager/lib/facter/rhsm_identity.rb ~/lib/facter
facter rhsm_identity (no output)

Edit rhsm_identity.rb and comment out Confine and it works just fine.

**Comment by waveclaw** [comment]
What is the output of ruby -v on that system?

The confine in facter is supposed to not invoke the fact is [File.exist?](http://ruby-doc.org/core-2.2.0/File.html#method-c-exists-3F) call fails.   [File.exists?](http://ruby-doc.org/core-2.2.0/File.html#method-c-exists-3F) is the depricated call that was used for older Ruby instances.

While I'm completely rebuiling my lab, could you provide what the output of 'ls /usr/sbin/subscription-manager' was or is on the system where 'facter rhsm_identity' does not return anything?

**Comment by Ramorous** [comment]
[root@xyzhost ~]# ruby -v
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]


I did modify the File.exist? to File.exists? and still the same outcome.

**Comment by Ramorous** [comment]
[root@xyzhost ~]# ls /usr/sbin/subscription-manager
/usr/sbin/subscription-manager

**Comment by waveclaw** [comment]
Additional Testing shows this impacts all the facts and Ruby 1.93 and higher.  I am will be forced to move the conditional test out of confine for Facter 3 as well. Only symbol-based facts are operating with confine on Facter 3 and higher.

**Comment by waveclaw** [comment]
Conditional testing for facts was pushed into the 2.0.1 release and only awaits final testing.
