### ISSUE TITLE
Using subscription_manager with RedHat SAM (Subscription Asset Manager)

### ISSUE THREAD

**Issue by fduranti** [waveclaw/puppet-subscription_manager#33]
It seems i get some problem using the subscription_manager with RedHat SAM related to the packages it try to install.

The module use try to use "katello-ca-consumer-" package name instead SAM use "candlepin-cert-consumer-" package name. It would be nice if this parte of package name was configured as a parameter to pass to the class itself.

It's used in install.pp and 
[code]
$_pkg = "katello-ca-consumer-${::subscription_manager::server_hostname}"
  # four scenarios
  # I.  never registered
  #  - no ca_name
  #  - no identity
  #  - just install normally
  package { $_pkg:
    ensure   => 'latest',
    provider => 'rpm',
    source   =>
  "http://${::subscription_manager::server_hostname}/pub/katello-ca-consumer-latest.noarch.rpm",
  }
[/code]
I also had to change the rhsm_ca_name.rb fact to put the candlepin certificate name:
      cafile = '/etc/rhsm/ca/candlepin-local.pem'

**Comment by waveclaw** [comment]
Thank you for your request.  Do you have tests related to this that you can provide?

Can you provide a link to RedHat SAM documentation that you are using?

**Comment by waveclaw** [comment]
Reopen if the current changes do not work.  I do not have and cannot test SAM support.

**Comment by fduranti** [comment]
There's a wrong parameter on line 40 of install.pp. After getting this correct (and changing the $environment parameter to another name everywhere) it work correctly on RHEL7 with SAM1.4 on Puppet Enterprise 2016.2 (Later I'll put a Merge Request for the change of that variable ...hoping you can merge it in the module as it's working correctly after the change). I've tested the complete registration (with the catello-latest.rpm package to be installed and works correctly.

The wrong parameter is ${::ca_package_prefix} instead of ${::subscription_manager::ca_package_prefix} on this line:
  "http://${::subscription_manager::server_hostname}/pub/${::ca_package_prefix}latest.noarch.rpm",
Should become:
"http://${::subscription_manager::server_hostname}/pub/${::subscription_manager::ca_package_prefix}latest.noarch.rpm",

**Comment by waveclaw** [comment]
Thank you for catching the missing prefix.  I cannot merge any changes to the environment variable name for Puppet 4.

I'm going to have to post a 3.0 version for that since it involves a major change to the provider and public API used by people already.

**Comment by waveclaw** [comment]
Retarget Puppet 4 release (e.g. version 3.0)

**Comment by nmaludy** [comment]
This also just bit me. Any update on a release for Puppet 3 (i'm using puppet 3.6)?

**Comment by waveclaw** [comment]
The actual fix for this is going into the Puppet 4 branch.  I'm off doing other things right now so have been delayed in testing for release.  I do not have an ETA on returning to finish the Puppet 4 work.

Sadly, I don't have Puppet 3.6 to test. The test infrastructure I use in the module dropped support for Puppet bellow 4 months ago.  As I asked for in the comments, I welcome any test results from people with SAM. I also now ask for those with live older Puppet infrastructure to submit reports.

The API for the package includes that parameter, `$ca_package_prefix`.  It is a documented option on the main class in the released version.

This parameter is reported by the Puppet Enterprise console for the module. The option is visible as a top-level variable in other consoles like F/OSS puppet and The Foreman or Katello.

I do not consider using that a workaround but actually applying the supported API.

If that is actually working for you then I would consider this issue resolved through use of the API by end users.  

If there is a problem with the documentation of this feature please let me know.

**Comment by fduranti** [comment]
As the puppet 4 branch have no ETA, do you think it's possible to do a version and publish it with the fix that will let subscription-manager work with puppet 4 (and all PE2016-2017)?
The only thing that need a fix to let it work is the $environment parameter that should be renamed to anything else (smenvironment or smenv or any name you like). 
This will fix the problem and let the module work with puppet 4 (I've used it in PE2016.4/5 and now I'm using in PE2017.1.1).

If you want I can do a new PR with the needed changes.

**Comment by waveclaw** [comment]
I'm actually trying to do the last tests today.  I've got good Satellite 6 tests and updates to the pre-requistites and a "final" Puppet 3 version on the forge.

Getting a working Katello 3.3 system has been a month long joke of issues, though.  Presuming there are no more surprises - like the behavior of the user and password options in native types - the code now in head is what I hope to ship.

If you have any tests results or bug reports  I would be happy to review them.



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by fduranti** [comment]
Good to know :) The code is the one in the puppet-4 branch? Tomorrow I'll try to give it a fast run on rhel5-6-7 servers over SAM 1.4 configuring pulp as repo manager and let you know if all is working correctly.

**Comment by waveclaw** [comment]
Testing with Katello 3.3 shows that this module is able to trigger registration and appropriate facts get created. 

The results of SAM testing are all I need to push this to the forge.

**Comment by fduranti** [comment]
Just doing some test... should have some good result between now and tomorrow morning (EU time).
For now I've just configured a single host and it seems to work but tomorrow I should get some more also with different release (rhel5-6-7).

One problem I seem to get is trying to undefine the server.proxy_hostname (to delete a proxy I can have configured in the past and that should not be used).

In the config_hash i pass this:
```
config_hash:
    server_proxy_hostname: ''
```
It will reset to empty string the value in the config file correctly if present but at the next run it will try to change it and it will try to change it every run as if it find something different:

```
Notice: /Stage[main]/Subscription_manager::Config/Rhsm_config[/etc/rhsm/rhsm.conf]/server_proxy_hostname: defined 'server_proxy_hostname' as '' 
```

Running with noop it say that the current value is absent and should be "":
```
Notice: /Stage[main]/Subscription_manager::Config/Rhsm_config[/etc/rhsm/rhsm.conf]/server_proxy_hostname: current_value absent, should be  (noop)
```

**Comment by waveclaw** [comment]
This looks like  the sync bug in Puppet 3.3.  rhsm_config's provider is a prefetch provider.  It is supposed to parse the whole config in one go.  It should only flush the configuration to disk if there is a difference.

I can integration test for this seperate from the subscription support.  I would open a new issue.  Return of always-changing node status is a blocker for release.



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by fduranti** [comment]
This was also happening with the old 2.2.1 version for me, the problem seems only related to empty value, if I put a value there it works correctly but if I put an empty value it try to change it because it seems that he try to check empty string with absent (i think it's undef) and they are different. 

I'm running on PE2017.1.1 on puppet agent 1.9.3 on rhel 7. Tomorrow morning I'll do some more checks on this too.

**Comment by fduranti** [comment]
Done some more tests, I've configured 30-40 machines with SAM 1.4 on puppet PE 2017.1.1 and all seems to work correctly if not defining the server_proxy_hostname parameter = ''.

I can confirm that passing a "real" proxy hostname work correctly (it will change it at the first run:
NOOP RUN:
`Notice: /Stage[main]/Subscription_manager::Config/Rhsm_config[/etc/rhsm/rhsm.conf]/server_proxy_hostname: current_value absent, should be proxy.domain.com (noop)
`
REAL RUN:
`Notice: /Stage[main]/Subscription_manager::Config/Rhsm_config[/etc/rhsm/rhsm.conf]/server_proxy_hostname: defined 'server_proxy_hostname' as 'proxy.domain.com'
Info: Class[Subscription_manager::Config]: Scheduling refresh of Class[Subscription_manager::Service]
Info: Class[Subscription_manager::Service]: Scheduling refresh of Service[rhsmcertd]
Notice: /Stage[main]/Subscription_manager::Service/Service[rhsmcertd]: Triggered 'refresh' from 1 events
Notice: Applied catalog in 1.36 seconds
`
Using undef as value will result in nothing changed (but also nothing removed) exactly as the parameter was not set:
`    config_hash:
      server_proxy_hostname: ~
`

Using a '' value in the hash:
`    config_hash:
      server_proxy_hostname: ''
`

NOOP RUN: 
`Notice: /Stage[main]/Subscription_manager::Config/Rhsm_config[/etc/rhsm/rhsm.conf]/server_proxy_hostname: current_value proxy.domain.com, should be  (noop)
`

NORMAL RUN:
`Notice: /Stage[main]/Subscription_manager::Config/Rhsm_config[/etc/rhsm/rhsm.conf]/server_proxy_hostname: server_proxy_hostname changed 'itrompx10.q8int.com' to ''
`

The value is changed into the file and removed from the config line:
`proxy_hostname =
`

Running it after the change will result in the resource being "changed" again and again (it seems that it's seeing the absence of the parameter but absent != '' and try to change it again):
NOOP RUN:
`Notice: /Stage[main]/Subscription_manager::Config/Rhsm_config[/etc/rhsm/rhsm.conf]/server_proxy_hostname: current_value absent, should be  (noop)
`
NORMAL RUN:
`Notice: /Stage[main]/Subscription_manager::Config/Rhsm_config[/etc/rhsm/rhsm.conf]/server_proxy_hostname: defined 'server_proxy_hostname' as ''
Info: Class[Subscription_manager::Config]: Scheduling refresh of Class[Subscription_manager::Service]
Info: Class[Subscription_manager::Service]: Scheduling refresh of Service[rhsmcertd]
`

**Comment by waveclaw** [comment]
Please test the string update in 80cbd1b03 if you can. I'm considering this a release candidate at this time.  My manual acceptance tests on this version are passing.

This issue with empty parameters causing the configuration to never settle appears to be an interaction of the old handmade configuration parser, the stub create in the providers and the `build_config_parameters` helper function. 

I've re-written all three to use strings for unset parameters instead of 'nil.'  This causes all the parameters from `puppet resource rhsm_config` to promote to strings.  However, this keeps Puppet 4's internals from mis-identifying an empty string parameter as different from a `nil` parameter.  Tests on CentOS 7 show that these stringly-typed unset parameters do not trigger the false need to flush the configuration to disk.

 Puppet's RAL does not seem to care that boolean or numeric types receive empty strings from the provider instead of nil when not set.  The type enforcement appears to be ignoring this. This might be a bug, but works well.   Numeric and boolean parameters could be set to empty strings.  Thus they were never able to be given empty-strings to trigger the behavior. 

I expect that output of `puppet resource rhsm_config` will need massaging.  The raw output will  pass the type restrictions on the parameters.  Puppet 4 seems to ignore validation completely on the resource.   But string parameters on numeric parameters causes the 'never sync' issue.  Someone could implement munging for numeric and boolean types to accept strings.

**Comment by fduranti** [comment]
ok I'll test it and see what happen. I'll let you know as soon as I've done the tests.

**Comment by fduranti** [comment]
Tested and it worked correctly (changing a proxy to "" and then it will not try to change it again).

**Comment by waveclaw** [comment]
Thank you for testing the updated parser
