### ISSUE TITLE
rhsm_pool id regex only works with ruby 2

### ISSUE THREAD

**Issue by robert4man** [waveclaw/puppet-subscription_manager#35]
unless value =~ /^\h+$/ causes an issue for RHEL5&6 under ruby 1.8

The \h regex only works in ruby 2. It should probably be replaced with /^[0-9a-fA-F]+$/ to continue to support RHEL5&6. Furthermore, the Travis tests should probably include ruby 1.8.7 for the same reason.

**Comment by belminf** [comment]
Came on here to report this bug :-)
