### ISSUE TITLE
support proxy settings

### ISSUE THREAD

**Issue by pgassmann** [waveclaw/puppet-subscription_manager#43]
proxy options in server section of rhsm.conf currently cannot be managed with this module. 

Manual configuration is possible when #41 is merged. Issue #40

**Comment by waveclaw** [comment]
Proxies are supported in configuration but were not documented correctly.

This is being documented in the puppet-4 branch.  

With your changes to resolve #40 they do not break rhsm_register when present.

**Comment by waveclaw** [comment]
Patches Included with 3.x
