### ISSUE TITLE
Issue with CA Name not matching satellite/katello hostname

### ISSUE THREAD

**Issue by dannygoulder** [waveclaw/puppet-subscription_manager#51]
In our environment we have replaced the SSL certificates for the satellite/katello API/web interfaces with custom CA certificates.

This means that the CN of the ca certificate is the name of our custom CA and not the hostname of the server.  It looks like rhsm_ca_name originates from the CN of the ca certificate and this breaks the detection of whether rhsm is registered already or not.

Perhaps we need a new fact, read from `grep "^hostname = " /etc/rhsm/rhsm.conf`, and to perform an additional check to whether this fact matches the name in the RPM?

Happy to help out with a PR if this is an agreed approach.

**Comment by dannygoulder** [comment]
OK - seems I am learning this backwards.  I have been managing systems by using existing rhsm bootstrap scripts and using this module to manage pools and repos to date.  Now trying to eliminate the bootstrap script and just use this module.  So I have just realised that rhsm.conf is actually managed by this module (by passing the server_hostname parameter).

So we could use the server_hostname directly in config.pp but this might require some rework in quite a few places.

Also I find that when using a custom CA we get two PEM files in /etc/rhsm/ca/ - `katello-default-ca.pem` and `katello-server-ca.pem`.

The CN of katello-default-ca.pem _does_ match the server hostname.

Looking at my old katello-ca-consumer rpms from before I replaced the certificate, there was just a single file named katello-server-ca.pem.  Perhaps the rhsm_ca_name fact should take the CN from katello-default-ca.pem if it exists, otherwise fall back to katello-server-ca.pem

**Comment by waveclaw** [comment]
You should always be explicit about where the certificate names originate. 

The CA certificates can be completely different from the internal CA certificates provided by a Katello server hosted RPM.  You can even name them whatever you want and force the matter. Connection to RHN (RedHat Network,) a Satellite Proxy or use with SAM (Subscription Access Manager) are impacted by other certificates and use various naming schemes. There are even a host of issues caused when legacy RHN 69.pem files still exist from Satellite 5 or Spacewalk.

As much as possible this module works as a fancy wrapper around subscription-manager commands and output.  Even then some custom parsing has to be done.   But as long as the SSL certificates function (e.g. `/sbin/subscription-manger status` does not return errors) I would consider differing names a valid configuration.  

Consider a number of CNAMES for a server that is using subjectAltName on a v3_req extension in the SSL certificate.  Which one of these is the server's name?  The commonName could even be a nonsensical internal ID.  As long as at least one name matches SSL will not care.

However, if you really do want a fact just to handle you case, one would not be rejected outright.   I would not want to make the configuration dependant on a hand parsed certificate probe, though. The user should be considered 'correct and right' about what the name of the server should be.

**Comment by dannygoulder** [comment]
Thanks for the reply.  When you say 

> I would not want to make the configuration dependant on a hand parsed certificate probe...

Is that not what is happening in the [fact](https://github.com/waveclaw/puppet-subscription_manager/blob/e7ebbc4d886a46b5389703bbfb342cb972793bb0/lib/facter/rhsm_ca_name.rb#L21-L23) and the [module](https://github.com/waveclaw/puppet-subscription_manager/blob/e7ebbc4d886a46b5389703bbfb342cb972793bb0/manifests/install.pp#L49)?

It looks like the expectation of the `rhsm_ca_name` fact is that it match the server hostname given how it is used in install.pp?  Is my understanding correct?

In my use-case we have an intermediate CA issuing the Katello certificate (which we are passing to `katello-installer --certs-server-cert --certs-server-ca-cert` et al).  This causes the `katello-server-ca.pem` on the clients to be the custom CA certificate, and the original `katello-server-ca.pem` cert appears in `katello-default-ca.pem`.  Since the custom CA certificate's subject contains a string like `CN=My Custom CA 123` the `rhsm_ca_name` fact ends up set to that CA name which prevents install.pp from working as designed.

What I am proposing simply uses the `katello-default-ca.pem` file (if present) in preference to the `katello-server-ca.pem` file.  I will be testing (manually) from my fork in the next week or so, and if I have success I will send a PR.  I might try to expand the tests to cover my specific use-case as well, given sufficient time.

I may have to think of a better way to explain what I am trying to do - but perhaps a PR is worth a thousand words - is that a cliché yet?

**Comment by dannygoulder** [comment]
BTW I am using Satellite 6.2 (upgraded from 6.0 through 6.1, but the CA certificates were replaced when it was 6.1).  I have noticed that newly-minted katello-ca-consumer RPMs (on a fresh 6.2 install) appear to package a shell script that creates the `/etc/rhsm/ca/katello*.pem` files, while 6.0/6.1 era RPMs deliver these files directly.  Not sure if that makes a whole lot of difference to how the module operates, though.

I am not using foreman/katello upstream versions so I don't know how those behave with custom CA certs, but I guess the corresponding upstream versions will behave similarly.

**Comment by waveclaw** [comment]
> Is that not what is happening in the fact and the module?

That is  used to detect _re_registration, or Case III.  That is also only relevant if you use the module's convenience classes to do the work for you.

In your case I would recommend instead using the rhsm_* resources directly.  You are changing the CA name on purpose so are no longer doing something that can be supported by the simple classes in the module.

**Comment by dannygoulder** [comment]
Thanks for the reply.  I did some more experimentation but met with limited success.

I tried to use rhsm_* resources exclusively but it seems like rhsm_ca_name is used throughout the module ([in the rhsm_register resource](https://github.com/waveclaw/puppet-subscription_manager/blob/e7ebbc4d886a46b5389703bbfb342cb972793bb0/lib/puppet/provider/rhsm_register/subscription_manager.rb#L227-L234) as well as the convenience classes).

I appreciate that I have changed the CA name on purpose, but this is a [documented](https://access.redhat.com/documentation/en-US/Red_Hat_Satellite/6.0/html/Installation_Guide/sect-Red_Hat_Satellite-Installation_Guide-Configuring_RednbspHat_Satellite_with_a_Custom_Server_Certificate.html) process.  I'm sure there are others who have done this too.

So, I've sent #52 which if applied means (for someone using a custom CA certificate with katello or Satellite) that the rhsm_ca_name fact now matches the hostname part of the katello-ca-consumer rpm. It appears from the API doco in the rhsm_register provider that this is the expected value of this fact, so hopefully this is an acceptable enhancement.

Thanks again for your replies to this issue.

**Comment by waveclaw** [comment]
I'm not able to replicate your issue in my lab.   We do replace the CA name and do not see this particular error.

However, with the additional work you have done to refacter the update, provide a passing unit test and to take the time to research this I no longer have objections to the merge reqest #52
