### ISSUE TITLE
Calling subscription-manager via consolehelper strips environment variables

### ISSUE THREAD

**Issue by antevens** [waveclaw/puppet-subscription_manager#57]
I recently came across an issue where on Centos 6.X the puppet subscription-manager module would not work when proxy settings were required and set via environment variables.

It turns out the default PATH for puppet does not prefer /usr/sbin over /usr/bin which means that when the subscription-manager command is called it's actually calling the consolehelper version:

[root@sdecentos6proxyonlydev]# file /usr/bin/subscription-manager 
[root@sdecentos6proxyonlydev]# /usr/bin/subscription-manager: symbolic link to `/usr/bin/consolehelper'

Sadly consolehelper strips all environment variables so no proxy settings are preserved, I modified the python code to print out all environment variables:

[root@sdecentos6proxyonlydev]# /usr/bin/subscription-manager 
{'LANG': 'en_US.UTF-8', 'USERHELPER_UID': '0', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'LOGNAME': 'root', 'USER': 'root', 'HOME': '/root', 'PATH': '/usr/sbin:/usr/bin:/sbin:/bin:/root/bin'}
Usage: subscription-manager MODULE-NAME [MODULE-OPTIONS] [--help]

[root@sdecentos6proxyonlydev]# /usr/sbin/subscription-manager 
{'HTTP_PROXY': 'http://172.30.0.2:3128/', 'NO_PROXY': 'localhost,127.0.0.1', 'http_proxy': 'http://172.30.0.2:3128/', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'LOGNAME': 'root', 'USER': 'root', 'HOME': '/root', 'PATH': '/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin:/root/bin', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'SHLVL': '1', 'G_BROKEN_FILENAMES': '1', 'HISTSIZE': '1000', 'https_proxy': 'http://172.30.0.2:3128/', 'no_proxy': 'localhost,127.0.0.1', '_': '/usr/sbin/subscription-manager', 'OLDPWD': '/etc/puppet/environments/4.5.61/dist', 'HOSTNAME': 'sdecentos6proxyonlydev', 'HISTCONTROL': 'ignoredups', 'HTTPS_PROXY': 'http://172.30.0.2:3128/', 'PWD': '/etc/puppet/environments/4.5.61', 'MAIL': '/var/spool/mail/root'}
Usage: subscription-manager MODULE-NAME [MODULE-OPTIONS] [--help]

I suggest replacing all instances of:

commands :subscription_manager => "subscription-manager"

with:

commands :subscription_manager => "/usr/sbin/subscription-manager"

Let me know if you prefer an MR but since it's a pretty simple change I figured I'd start with an issue report.

**Comment by waveclaw** [comment]
Striping of environment variables is a desired feature.  I do not support using that to configure things with the providers for this module.  Either the settings are provided via the existing rhsm.conf file or through the type interface for rhsm_config that manages that file.

You are free to fork the module and change that in your fork if you wish.
