### ISSUE TITLE
Error installing package ($_pkg) - v2.2.2

### ISSUE THREAD

**Issue by Edmilson-JR** [waveclaw/puppet-subscription_manager#61]
Hi Waveclaw,

Do you still update code for Puppet 3 ?

If so, I'd like to do a PR to fix the following:

Agent's execution is returning an error at https://github.com/waveclaw/puppet-subscription_manager/blob/v2.2.2/manifests/install.pp#L41

The value provided to `source` attribute misses `::subscription_manager` before `::ca_package_prefix`, so Puppet can't find that package.

**Comment by waveclaw** [comment]
I do not actively maintain any Puppet 3 code bases anymore.  I can review and accept non-conflicting Puppet 3 fixes, but the Puppet 3 code is no longer tested against or reviewed.

**Comment by Edmilson-JR** [comment]
Ok, thank you.

I'll do all the tests locally before the PR.

**Comment by waveclaw** [comment]
Do note that I may not be able to upload a module based on any 2.x tags or versions to the Puppet Forge.

**Comment by waveclaw** [comment]
Puppet 3 is EOSL and no longer supported.
