### ISSUE TITLE
subscription-manager identity does not scale

### ISSUE THREAD

**Issue by sean797** [waveclaw/puppet-subscription_manager#63]
Currently, this relies on running `subscription-manager identity` [1] This makes a request to the RHSM Server everytime it runs, which can result is effectively DDOS'ing a Satellite Server if you have a large number of clients.

In my testing with 8000 clients and a Satellite 6 with 128GB RAM / 16 VCPUs, made any problem with the Satellite extremely hard to recover due to the traffic. I think a more scalable approach would be to parse the contents of `/var/lib/rhsm/cache/` ?

[1] https://github.com/waveclaw/puppet-subscription_manager/blob/master/lib/facter/rhsm_identity.rb

**Comment by ralfbosz** [comment]
Just wanted to create the same issue, would love to see this fact also use the cacheable-module like some of the other facts.

**Comment by ralfbosz** [comment]
I added caching in a PR...

**Comment by sean797** [comment]
thanks @ralfbosz :+1:
