### ISSUE TITLE
Feature: manage rhsmcertd service

### ISSUE THREAD

**Issue by jcpunk** [waveclaw/puppet-subscription_manager#66]
It would be nice if this module also managed rhsmcertd to ensure any new subscriptions are added to the box within a regular interval.

**Comment by waveclaw** [comment]
That is out of scope for a wrapper around subscription-manager.

A better idea is to build a rhsmcertd type and provider in a different project.

Teach Puppet how to manage the certificates directly or improve a different module that does certificate management to handle it.

The only way that subscriptions interact with the subscription_manager module is through the cleitn's subscription_manager API.
