### ISSUE TITLE
validation issues in puppet > 5.5

### ISSUE THREAD

**Issue by romz169** [waveclaw/puppet-subscription_manager#69]
I have figured out that in version 5.5 and higher I had to comment out the name option to get things to work. 

```
rhsm_pool {  'foo':
  ensure => present,
  name   => 'foo',
  id         => '007f477873373883893737',
  active   => true,
  }
```

> Parameter id failed on Rhsm_pool[foo]: Pool ID must be a hex number, was given foo

```
rhsm_pool {  'foo':
  ensure => present,
  #name   => 'foo',
  id         => '007f477873373883893737',
  active   => true,
  }
```
This passes fine. 

From some quick looking, between 4.10 and 5.5 then changed the behavior for namevar functionality. In 4.10 it looks like you are able set id to namevar and validate that. In 5.5 it looks like namevar is set to name if it is set.

**Comment by waveclaw** [comment]
Can you check this with release 4.5.0 and later? 

I cannot reproduce that behavior with Puppet 5.6.2 or 6.0.2.

**Comment by romz169** [comment]
using the code above I have tested this using PDK. Here are the steps I used to recreate the issue. 
pdk new module foo
cd foo
pdk new class foo
edit the .fixtures.yml to include this module. 
```
---
fixtures:
  forge_modules:
    subscription_manager: "waveclaw/subscription_manager"
```
drop that code in manifests/init.pp
```
class foo {
  rhsm_pool { 'foo':
    ensure => present,
    name   => 'foo',
    id     => '007f477873373883893737',
    active => true,
  }
}
```

pdk test unit --puppet-version[5.6.2,6.0.2] gets the following error: 

> error during compilation: Parameter id failed on Rhsm_pool[foo]: Validate method failed for class id: Pool ID must be a hex number, was given foo

Comment out the name and in init.pp and the pdk test unit passes fine.

**Comment by waveclaw** [comment]
The string 'foo' isn't a valid name.

```puppet
class foo {
  rhsm_pool { '007f477873373883893737':
    ensure => present,
    subscription_name   => 'foo',
    id     => '007f477873373883893737',
    active => true,
  }
}
```
would be the valid way to use the pool in your example.

This appears to be a documentation issue plus a problem with using custom `:namevar` settings.

I cannot drop the `name` field internally.  That causes pool resources to fail.  However, this "name" field is being used in your examples for what is properly called the `subscription_name`, which is not the proper name of the pool.  That is a human-friendly name.  The internal API does not use that when managing the resource, it uses the ID value.

I will update the documentation for release 5.
