### ISSUE TITLE
Are you planning a new release?

### ISSUE THREAD

**Issue by pietervandersluis** [waveclaw/puppet-subscription_manager#74]
I've noticed that your `master` has functionality for `rhsm_repomd_gpg_url` which is used in subscription-manager version 1.21.X

I've tested your master against 1.21.X and it seems to be working. I'll do more tests in the morning.

**Comment by pietervandersluis** [comment]
I did some more tests. The result:

Upgraded servers, work perfectly.
Not upgraded servers, result in ever changing runs.

**Comment by waveclaw** [comment]
Yes.  I am working on resolving the issues with the configuration application brought about by running rubocop against the codebase.

**Comment by pietervandersluis** [comment]
Great! Thank you.
