### ISSUE TITLE
Configuration error in /etc/rhsm/rhsm.conf

### ISSUE THREAD

**Issue by Edmilson-JR** [waveclaw/puppet-subscription_manager#78]
Hello,

I'm having a problem here with the `rhsm.conf` file.

First, sorry for this issue. I saw a [related one](https://github.com/waveclaw/puppet-subscription_manager/issues/59), but didn't find a solution there.

Also saw [this](https://github.com/waveclaw/puppet-subscription_manager/blob/v5.0.0/lib/puppet/type/rhsm_config.rb#L85) in `rhsm_config.rb` type, but it seems not to work (at least, not for me) because the string value is always written in the file.

Changed the value manually, but the next Puppet agent's execution changed it again to `false`.

`Notice: /Stage[main]/Subscription_manager::Config/Rhsm_config[/etc/rhsm/rhsm.conf]/rhsm_full_refresh_on_yum: rhsm_full_refresh_on_yum changed false to 'false'`

I've met the [requirements](https://github.com/waveclaw/puppet-subscription_manager#requirements) documented at `README`.

Is there any dependency that I missed for it to work?

Thanks

**Comment by Edmilson-JR** [comment]
@waveclaw 

Noticed that should be a `v5.1.0` for this module - [as written in forge.puppet.com](https://forge.puppet.com/waveclaw/subscription_manager) - , but didn't find it here at GitHub.

It seems to solve the problem mentioned in this issue.

Could you please publish it here?

**Comment by waveclaw** [comment]
No.
