### ISSUE TITLE
Non-existing repository throws nasty error

### ISSUE THREAD

**Issue by drag0nsden** [waveclaw/puppet-subscription_manager#82]
When I try to ensure a repository (either absent or present) that does not exist in Satellite (anymore), Puppet fails the entire catalog with:
`Failed to apply catalog: undefined method 'intern' for nil:NilClass` 
No mention anywhere as to which class produces the failure. Took me a few hours to sort it out.
Reproduce-able with declaring any rhsm_repo resource, with a repository that does not exist, for example:
`  rhsm_repo { 'myorg_Puppet_Puppet4':
    ensure => present,
  }`
The module should either fail, or warn that the repo does not exist, allowing the rest of the run to complete.

**Comment by waveclaw** [comment]
This is fixed by the changes from #81 ; the bug was introduced by the Rubocop clean up
