### ISSUE TITLE
Validate method failed for class name: undefined method `match?'

### ISSUE THREAD

**Issue by surcouf** [waveclaw/puppet-subscription_manager#84]
Hi, 
 Using Puppet 4.10 with Puppetserver 2.7 and subsciption_manager 5.1.1, I'm getting this following error : 
`Error: Failed to apply catalog: Parameter name failed on Rhsm_config[/etc/rhsm/rhsm.conf]: Validate method failed for class name: undefined method `match?' for "/etc/rhsm/rhsm.conf":String at /etc/puppetlabs/code/environments/project_rbordet/modules/subscription_manager/manifests/config.pp:57`

Regards,

**Comment by waveclaw** [comment]
The version of Ruby for Puppet 4.10 doesn't have `String.match?`.  This is why I deprecated support in the 4.x series and dropped in 5.0.
