### ISSUE TITLE
Unregister

### ISSUE THREAD

**Issue by Shavindra** [waveclaw/puppet-subscription_manager#85]
I don't see the functionality to unregister only. Is it possible to add the functionality ?

**Comment by waveclaw** [comment]
Unregister is possible with the `rhsm_register` type.  Just ensure that the type is absent as you would any other type to trigger the unregister process.

f this does not work for you, please open a new ticket with details from your experience.

You cannot use the friendly wrapper classes for this. 

If you would like to write a `bolt` task for this, I can accept that merge request.  A task may be useful for large sites to wipe and re-register systems in bulk for those who prefer to use `bolt` between Puppet runs to force a known state.
