### ISSUE TITLE
RFC: Goferd service not needed

### ISSUE THREAD

**Issue by Ronaldschouw** [waveclaw/puppet-subscription_manager#88]
Hi 

Since satellite 6.2 is it possible to use katello-host-tools instead of katello-agent and gofer
See https://access.redhat.com/articles/3875321 and https://access.redhat.com/articles/3154811
As a workaround is it possible to overwrite the String $service_name = 'goferd',
It is possible to change the puppet-subscription_manager to a goferless operation ?

Regards,

Ronald Schouw
Linux engineer

**Comment by waveclaw** [comment]
Yes, you can replace the service_name parameter or even undefine that value.

You can also use the native types inside the classes to directly register without depending on gofer.  I provide the classes as a convenience wrapper for the typical use case and legacy users.  If you need to customize your deployment please do so.

Note that I don't test on a gofer-less environment. Satellite 6.2.11 and later can do gofer-less package management. Without access to Satellite 6.2.11 I cannot verify the results.
