### ISSUE TITLE
rhsm_repo resource doesn't use the cache files.

### ISSUE THREAD

**Issue by cornell80** [waveclaw/puppet-subscription_manager#89]
Our organisation use this module to manage the repo's from Satellite 6 (+/-2500 systems) with the "rhsm_repo" resource.  
But with every puppet run the rhsm_repo execute "subscription-manager repos" which in turn does a call to the Satellite server.
```
Debug: Prefetching subscription_manager resources for rhsm_repo
Debug: Executing: '/sbin/subscription-manager repos'
```
This generate a load of trafic and cpu time on the Satellite server.  
Is there a reason why the rhsm_repo resource doesn't use the cache files (if available) in /var/cache/rhsm ?

**Comment by waveclaw** [comment]
This module does use `/var/cache/rhsm`.  The module abstracts the `subscription-manager` command.  If this command on your systems is not using the cache for the repos command but refreshing every time then this module will refresh every time.
