### ISSUE TITLE
RHEL 7.8: Getting already attached pools not working

### ISSUE THREAD

**Issue by mungo312** [waveclaw/puppet-subscription_manager#98]
After Updating to RHEL7.8 the module can not get the already attached pools.

After some investigation I think the problem is that the `/usr/sbin/subscription-manager list --consumed` command does not produce a line `System Type`, it is now called `Entitlement Type`.
Because of this the current subscription is never added to the array of subscriptions.

If nobody else is faster I will try to provide a badly tested pull request.

**Comment by waveclaw** [comment]
Duplicates #99 which has an untested patch to check
